### ISSUE TITLE
The RAG LLM Assistant Breaks out of the box on indexing

### ISSUE THREAD

**Issue by vinooganesh** [Snowflake-Labs/sfquickstarts#1069]
**Describe the bug**
The RAG LLM Assistant Breaks out of the box on indexing

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/build_rag_based_blog_ai_assistant_using_streamlit_openai_and_llamaindex/index.html?index=..%2F..index#3

**To Reproduce**
1. Follow the steps in the linked quickstart
2. Upon running `build_index.py` the operation fails 

```bash
(venv) ~/git/sfguide-blog-ai-assistant/.content/blogs (main) $ ls                                                                
cloud_native_data_engineering_with_matillion_and_snowflake.md    data_engineering_with_snowpark_python_and_dbt.md
data_engineering_pipelines_with_snowpark_python.md               getting_started_with_dataengineering_ml_using_snowpark_python.md
data_engineering_with_apache_airflow.md
(venv) ~/git/sfguide-blog-ai-assistant (main) $ python build_index.py
Building vector index...
Traceback (most recent call last):
  File "/Users/vinooganesh/git/sfguide-blog-ai-assistant/build_index.py", line 40, in <module>
    main()
  File "/Users/vinooganesh/git/sfguide-blog-ai-assistant/build_index.py", line 36, in main
    build_index(data_dir, knowledge_base_dir)
  File "/Users/vinooganesh/git/sfguide-blog-ai-assistant/build_index.py", line 21, in build_index
    documents = SimpleDirectoryReader(data_dir).load_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinooganesh/git/sfguide-blog-ai-assistant/venv/lib/python3.11/site-packages/llama_index/readers/file/base.py", line 149, in __init__
    self.input_files = self._add_files(self.input_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinooganesh/git/sfguide-blog-ai-assistant/venv/lib/python3.11/site-packages/llama_index/readers/file/base.py", line 209, in _add_files
    raise ValueError(f"No files found in {input_dir}.")
ValueError: No files found in .content/blogs.
```

**Expected behavior**
The blogs exist in the `.content/blogs` directory, I would expect files to be found.

**Desktop (please complete the following information):**
MacOS Sonoma 14.2.1 

**Additional context**

**Comment by bennyhartnett** [comment]
same
