### ISSUE TITLE
Leverage dbt Cloud to Generate ML ready pipelines using Snowpark python - code fails at step 8 in dbt

### ISSUE THREAD

**Issue by beata9876** [Snowflake-Labs/sfquickstarts#1135]
I'm trying to complete step 8 but unfortunately it fails inside dbt at node "ml_data_prep":
<img width="601" alt="image" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/164160340/07624cab-0dee-4217-b23b-324215e5a404">

The begining of the error:
$$
CALL ml_data_prep__dbt_sp();
20:46:38 Opening a new connection, currently in state closed
20:47:08 Snowflake adapter: Snowflake query id: 01b31f1e-0000-ad79-0000-00008f71a371
20:47:08 Snowflake adapter: Snowflake error: 100357 (P0000): Python Interpreter Error:
Traceback (most recent call last):
  File "_udf_code.py", line 151, in main
  File "_udf_code.py", line 36, in model
  File "/usr/lib/python_udf/f4e509cd372a09942abc6ef933b2ac5b1a7b1eb2a9f369fd8e4df343ffe35c5c/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 2263, in sum
    result = self._agg_general(

And the end of the log file:
<img width="578" alt="image" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/164160340/45367ec5-6d61-4ee7-8628-577be13acab6">

**Comment by sfc-gh-cweidmann** [comment]
There is a quick fix to this: 

In `models/ml/prep_encoding_splitting/ml_data_prep.py` replace line 5
`dbt.config(packages=["pandas"])` with `dbt.config(packages=["pandas==1.5.3"])`

Repeat this with the file `models/ml/prep_encoding_splitting/covariate_encoding.py` and replace line 8
`dbt.config(packages=["pandas“,"numpy","scikit-learn"])` with `dbt.config(packages=["pandas==1.5.3","numpy","scikit-learn"])`

After saving these two changes, the 'dbt build' should run successfully and everything should work as expected. 

We are working with dbt to fix this Quickstart guide.

**Comment by beata9876** [comment]
Success! Thanks a lot :)
