### ISSUE TITLE
Please help me with this error

### ISSUE THREAD

**Issue by kartheek91** [Snowflake-Labs/sfquickstarts#1156]
Broken DAG: [/usr/local/airflow/dags/my_cosmos_dag.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/airflow/dags/my_cosmos_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'

**Comment by datteswararao** [comment]
Broken DAG: [/usr/local/airflow/dags/my_cosmos_dag.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cosmos/converter.py", line 214, in __init__
    project_config.validate_project()
  File "/usr/local/lib/python3.9/site-packages/cosmos/config.py", line 207, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /Users/GrayMatter/snowpark/dbt_airflow/dags/dbt/cosmosproject/dbt_project.yml
