### ISSUE TITLE
Url should be a scoped URL (Snowflake for Data Lake / 5. Unstructured Data)

### ISSUE THREAD

**Issue by jimnicholls** [Snowflake-Labs/sfquickstarts#1254]
At the end of [section 5 of the Snowflake for Data Lake guide](https://quickstarts.snowflake.com/guide/vhol_data_lake/index.html#4), there is this query to extract the text from the PDFs.

```sql
select
  relative_path,
  file_url,
  read_pdf('@documents/' || relative_path)
from directory(@documents)
limit 5;
```

The query fails with a `100315 (P0000): User Error Report:`.

```text
Java Stack Trace:
java.io.IOException: Url should be a scoped URL. If you are expecting an owner file here indicate so in the SDK. for file '@documentsNeurIPS-2020-a-graph-similarity-for-deep-learning-Paper.pdf'
	at com.snowflake.udf.RemoteError.<init>(RemoteError.java:16)
	at com.snowflake.udf.SfInputStream.openStream(Native Method)
	at com.snowflake.udf.SfInputStream.<init>(SfInputStream.java:128)
	at com.snowflake.udf.SfInputStream.create(SfInputStream.java:111)
	at com.snowflake.udf.SfInputStream.create(SfInputStream.java:90)
 in function READ_PDF with handler PdfParser.ReadFile
```

**Comment by jimnicholls** [comment]
This appears to be because of [bcr-1008](https://docs.snowflake.com/en/release-notes/bcr-bundles/2023_03/bcr-1008), introduced in the 2023_03 bundle.
