### ISSUE TITLE
Bug when executing Streamlit app in Quickstart 'Getting Started with Cortex Analyst: Augment BI with AI'

### ISSUE THREAD

**Issue by sfc-gh-rpughsley** [Snowflake-Labs/sfquickstarts#1755]
**Describe the bug**
After following up to step 5, pasting the streamlit code into Snowsight, and running it,I get an error

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/getting_started_with_cortex_analyst/index.html#4

**To Reproduce**
1. Follow up to step 5, then copy/paste the streamlit code
2. Execute the streamlit app
3. Execute a suggested query with Cortex

**Expected behavior**
A result / answer returned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.7.1
 - Browser : Prisma Access
 - Version 

**Additional context**
here is the error:
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at rc (https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/main.74bb1dff.js:2:2299285)
at ns (https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/main.74bb1dff.js:2:2264578)
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:149812
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:279974
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:222567
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:222782
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:218897
at https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/6950.70fe55c2.chunk.js:2:219172
at ol (https://app.snowflake.com/static/streamlit/1.35.0-sa.3/static/js/main.74bb1dff.js:2:2289801)
at yl (https://app.snowflake.com/static/streamlit/1.35.0-sa.3/stati
![2024-11-27_12-25-15](https://github.com/user-attachments/assets/0c06d8e4-2e55-4e68-aa51-fdf82a053f16)

**Comment by iamontheinet** [comment]
@sfc-gh-cbaechtold Pl look into this issue.
