### ISSUE TITLE
[_]*/*.md open [_]*/*.md: The filename, directory name, or volume label 

### ISSUE THREAD

**Issue by rajeshpleti** [Snowflake-Labs/sfquickstarts#388]
https://github.com/Snowflake-Labs/sfquickstarts, trying to run through windows 

 npm run serve

> serve
> gulp serve

[17:13:04] Using gulpfile ~\Desktop\sfquickstarts\site\gulpfile.js
[17:13:04] Starting 'serve'...
[17:13:04] Starting 'build'...
[17:13:04] Starting 'clean'...
[17:13:04] Starting 'clean:codelabs'...
[17:13:04] Starting 'clean:build'...
[17:13:04] Starting 'clean:dist'...
[17:13:04] Finished 'clean:codelabs' after 7.05 ms
[17:13:04] Finished 'clean:build' after 7.35 ms
[17:13:04] Finished 'clean:dist' after 7.31 ms
[17:13:04] Finished 'clean' after 8.17 ms
[17:13:04] Starting 'build:codelabs'...
[17:13:04] Starting 'export:codelabs'...
err     [_]*/*.md open [_]*/*.md: The filename, directory name, or volume label syntax is incorrect.
[17:13:04] 'export:codelabs' errored after 65 ms
[17:13:04] Error: 1
    at ChildProcess.<anonymous> (C:\Users\rajesh.pasupuleti\Desktop\sfquickstarts\site\tasks\helpers\claat.js:21:13)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    at Process.callbackTrampoline (internal/async_hooks.js:131:14)
[17:13:04] 'build:codelabs' errored after 66 ms
[17:13:04] 'build' errored after 75 ms
[17:13:04] 'serve' errored after 76 ms

**Comment by jpramayo** [comment]
Hi @rajeshpleti 
Have you found a solution/workaround ?
thanks
