### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /sfquickstarts/site/node_modules/del/index.js

### ISSUE THREAD

**Issue by rajeshpleti** [Snowflake-Labs/sfquickstarts#389]
Hi,

I am getting below error while trying to run "npm run serve" command from site folder. I am trying to setup on Centos operating system.

# npm run serve

> serve
> gulp serve

internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /sfquickstarts/site/node_modules/del/index.js
require() of ES modules is not supported.
require() of /sfquickstarts/site/node_modules/del/index.js from /sfquickstarts/site/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /sfquickstarts/site/node_modules/del/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/sfquickstarts/site/gulpfile.js:33:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}

Please help me how to resolve the issue.

Thanking you in advance.

Thanks,
Anil.

**Comment by rajeshpleti** [comment]
perform the following steps to resolve issue

rm -rf cloud_native_data_engineering_with_matillion_and_snowflake
rm -rf end_to_end_machine_learning_with_dataiku

rm -rf accelerating_data_teams_with_snowflake_and_dbt_cloud_hands_on_lab
