### ISSUE TITLE
Getting Started with Snowpark and the Dataframe API: Docker Container does not build.

### ISSUE THREAD

**Issue by andremolenaar** [Snowflake-Labs/sfquickstarts#571]
**Describe the bug**
When trying to create the docker container in Step 2 of the workshop, the creation fails with an error.

**Error I get when building the container**
 => ERROR [4/4] RUN jupyter labextension install jupyterlab-plotly@5.3.1                                                                                                                          0.5s
------
 > [4/4] RUN jupyter labextension install jupyterlab-plotly@5.3.1:
#7 0.445 Traceback (most recent call last):
#7 0.445   File "/opt/conda/bin/jupyter-labextension", line 5, in <module>
#7 0.445     from jupyterlab.labextensions import main
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
#7 0.445     from .labapp import LabApp
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
#7 0.445     from jupyter_server.serverapp import flags
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 59, in <module>
#7 0.445     from jupyter_client import KernelManager
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyter_client/__init__.py", line 8, in <module>
#7 0.445     from .asynchronous import AsyncKernelClient  # noqa
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
#7 0.445     from .client import AsyncKernelClient  # noqa
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 8, in <module>
#7 0.445     from ..channels import AsyncZMQSocketChannel, HBChannel
#7 0.445   File "/opt/conda/lib/python3.8/site-packages/jupyter_client/channels.py", line 12, in <module>
#7 0.445     from jupyter_core.utils import ensure_async
#7 0.445 ImportError: cannot import name 'ensure_async' from 'jupyter_core.utils' (/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py)
------
executor failed running [/bin/bash -o pipefail -c jupyter labextension install jupyterlab-plotly@5.3.1]: exit code: 1

**To Reproduce**
1. Install Docker Desktop
2. Open a terminal window
3. Execute the following commands in the terminal window:
cd ~
mkdir DockerImages
cd DockerImages
git clone https://github.com/Snowflake-Labs/sfguide_snowpark_on_jupyter.git
cd ~/DockerImages/sfguide_snowpark_on_jupyter/docker
docker build -t snowparklab .

**Expected behavior**
I would expect a docker container to build where a working jupyter notebook is present. 

**Screenshots**
<img width="1383" alt="Screenshot 2023-03-24 at 14 03 07" src="https://user-images.githubusercontent.com/16894938/227528637-33ec2520-3e08-4c39-b4dc-44c9b670f3fd.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 3.2.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sugiryo** [comment]
I'm getting the same error (MacOS Ventura 13.5.2 on M2).

**Comment by param302-coridors** [comment]
I am getting the same error, Ubuntu 22 LTS

**Comment by sfc-gh-reliu** [comment]
Customers got the same error. I also can reproduce.
