### ISSUE TITLE
Build and Deploy model 1_mfr_mlflow.ipynb - very last step to call the udf does not work in snowflake

### ISSUE THREAD

**Issue by sunny-sharma-datalytyx** [Snowflake-Labs/sfquickstarts#772]
**The title of the Quickstart:** Getting Started with Snowpark for Machine Learning on AzureML
**A link to the Quickstart:** https://quickstarts.snowflake.com/guide/example_matt_marzillo/index.html?index=..%2F..index

**Describe the bug**
I carefully followed the guide here: https://quickstarts.snowflake.com/guide/example_matt_marzillo/index.html?index=..%2F..index#6.

The code was working AOK early last week but then stopped working - I followed the guide several times over the weekend to ensure my AzureML environment was not the issue but I continued to get errors.

This code gives an error:
select predict_failure(AIR_TEMPERATURE_K,
       PROCESS_TEMPERATURE, ROTATIONAL_SPEED_RPM, TORQUE_NM,
       TOOL_WEAR_MIN, HUMIDITY_RELATIVE_AVG) as predicted_failure, * from maintenance_hum;

Snowflake error msg:
100357 (P0000): Python Interpreter Error:
Traceback (most recent call last):
  File "/home/udf/3706236/udf_py_2135661639.zip/udf_py_2135661639.py", line 56, in compute
    return lock_function_once(func, invoked)(df)
  File "/home/udf/3706236/udf_py_2135661639.zip/udf_py_2135661639.py", line 45, in wrapper
    result = f(*args, **kwargs)
  File "/tmp/ipykernel_6538/816194690.py", line 32, in predict_failure
  File "/anaconda/envs/sunny/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
  File "/tmp/ipykernel_6538/816194690.py", line 24, in load_model
  File "sklearn/tree/_tree.pyx", line 676, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1364, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
 in function PREDICT_FAILURE with handler udf_py_2135661639.compute

**URL of where you see the bug**

**To Reproduce**
1. Just follow the guide all the way through

**Expected behavior**
I should get a table with the predictions in it. https://quickstarts.snowflake.com/guide/example_matt_marzillo/img/ca930cf83653d6b8.png

**Comment by sunny-sharma-datalytyx** [comment]
I was able to workaround/solve the issue by doing the following steps in an AzureML terminal:

1. conda create -n any_name_env python=3.8
2. conda activate any_name_env
3. pip install pandas==1.5.3 scikit-learn==1.2.2 cachetools==4.2.2 notebook ipykernel azureml-mlflow azureml-core azureml-dataprep matplotlib
4. pip install snowflake-snowpark-python[pandas]
5. python -m ipykernel install --user --name=any_name_env
6. mkdir any_name_env
7. cd any_name_env
8. git clone https://github.com/Snowflake-Labs/sfguide-getting-started-with-snowpark-for-machine-learning-on-azureml

Both notebooks reference:
"warehouse": "SMALL_WH",
 "database":"MFR",

where as the quickstart references:
CREATE OR REPLACE WAREHOUSE HOL_WH WITH WAREHOUSE_SIZE='X-SMALL';
CREATE OR REPLACE DATABASE HOL_DB;

You need to pick one and be consistent - i went with HOL_WH and HOL_DB then searched and replaced all notebook text.

Also, 0_setup_data.ipynb creates a table named CITY_UDF using session.write_pandas(city_udi_df, table_name='CITY_UDF', auto_create_table=True, overwrite=True) - however, 1_mfr_mlflow.ipynb is looking for HUMIDITY_UDI using hum_udi_df = session.table('MFR.PUBLIC.HUMIDITY_UDI') - again, I just changed HUMIDITY_UDI to be CITY_UDF.

I could never get the setup.sh script to work properly whilst creating a new compute resource and using the Provision with script option - just ran it once in a terminal manually.

I will look at forking the repo and adding my changes.

Hope this helps others starting out with AzureML and Snowpark.

**Comment by sunny-sharma-datalytyx** [comment]
To see correct versions required for local environment, use these commands in Snowflake:
select * from information_schema.packages where (package_name = 'pandas' and language = 'python');
select * from information_schema.packages where (package_name = 'cachetools' and language = 'python');
select * from information_schema.packages where (package_name = 'scikit-learn' and language = 'python');
