### ISSUE TITLE
Saving and Loading ML Model in Snowpark

### ISSUE THREAD

**Issue by john-graves-les-mills** [Snowflake-Labs/sfquickstarts#837]
I'm aiming to follow
https://github.com/Snowflake-Labs/sfguide-getting-started-machine-learning/blob/main/hol/2_1_DEMO_model_building_scoring.ipynb
but with the slight difference that I DON'T want to both build my model and score new data in the same session.
How can I persist my model? 
I've tried joblib dump and load without success:
Traceback (most recent call last):
  File "_udf_code.py", line 13, in main
  File "/usr/lib/python_udf/267fe91623aff8e06639af23af568e8242ed4db8fe33c5f1849c62f3fb589b6e/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 647, in load
    with _read_fileobject(fobj, filename, mmap_mode) as fobj:
  File "/usr/lib/python_udf/267fe91623aff8e06639af23af568e8242ed4db8fe33c5f1849c62f3fb589b6e/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python_udf/267fe91623aff8e06639af23af568e8242ed4db8fe33c5f1849c62f3fb589b6e/lib/python3.8/site-packages/joblib/numpy_pickle_utils.py", line 149, in _read_fileobject
    compressor = _detect_compressor(fileobj)
  File "/usr/lib/python_udf/267fe91623aff8e06639af23af568e8242ed4db8fe33c5f1849c62f3fb589b6e/lib/python3.8/site-packages/joblib/numpy_pickle_utils.py", line 97, in _detect_compressor
    first_bytes = fileobj.read(max_prefix_len)
  File "/usr/lib/python_udf/267fe91623aff8e06639af23af568e8242ed4db8fe33c5f1849c62f3fb589b6e/lib/python3.8/site-packages/snowflake/snowpark/files.py", line 132, in read
    raise NotImplementedError(_DEFER_IMPLEMENTATION_ERR_MSG)
NotImplementedError: SnowflakeFile currently only works in UDF and Stored Procedures. It doesn't work locally yet.
 in function MY_PROCEDURE_20230828 with handler main
![SANITIZED_MY_PROCEDURE_AS_DEPLOYED](https://github.com/Snowflake-Labs/sfquickstarts/assets/120435305/7538a35c-5462-4c2f-970c-15d6adf71c6a)

**Comment by john-graves-les-mills** [comment]
This solved my issue:
```python
def main(session: snowpark.Session): 
    session.file.get("@MODEL_STAGE/my_model.joblib", "file:///tmp")
    with open("/tmp/my_model.joblib", 'rb') as file:
        clf2 = load(file)
```
