### ISSUE TITLE
Data Engineering Pipelines with Snowpark Python => Step 4 Load Raw by using script steps/02_load_raw.py got 

### ISSUE THREAD

**Issue by thanasitv** [Snowflake-Labs/sfquickstarts#978]
**Describe the bug**
After run Step 4 Load Raw by using script steps/02_load_raw.py got 
snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. Verify the account name is correct: myaccount.snowflakecomputing.com:443. HTTP 403: Forbidden

** 'https://quickstarts.snowflake.com/guide/data_engineering_pipelines_with_snowpark_python/index.html?index=..%2F..index#3'

**To Reproduce**
1. Go to 'https://quickstarts.snowflake.com/guide/data_engineering_pipelines_with_snowpark_python/index.html?index=..%2F..index#3'
2. Run the Script
To load the raw data, execute the steps/02_load_raw.py script. 
3. Scroll down to the last line after executed the command
snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. Verify the account name is correct: myaccount.snowflakecomputing.com:443. HTTP 403: Forbidden

**Expected behavior**

**Screenshots**
 
<img width="952" alt="SnowFlake_steps_02_load_raw py_Error" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/31183618/57c229a2-3baa-4050-ba7f-1f56179e5c18">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]    Microsoft Windows 11 Pro Version	10.0.22621 Build 22621
 - Browser [e.g. chrome, safari]    chrome
 - Version [e.g. 22]  chrome Version 119.0.6045.161 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

This occured in github codespace as followed in the step from virtual lab Data Engineering Pipelines with Snowpark Python

**Comment by thanasitv** [comment]
(snowflake-demo) @thanasitv ➜ /workspaces/sfguide-data-engineering-with-snowpark-python/steps (main) $ python 02_load_raw.py
Traceback (most recent call last):
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 250, in authenticate
    ret = self._rest._post_request(
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 730, in _post_request
    ret = self.fetch(
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 849, in fetch
    ret = self._request_exec_wrapper(
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 987, in _request_exec_wrapper
    raise e
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 891, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 1189, in _request_exec
    raise err
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/network.py", line 1110, in _request_exec
    raise ForbiddenError
snowflake.connector.errors.ForbiddenError: HTTP 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/sfguide-data-engineering-with-snowpark-python/steps/02_load_raw.py", line 76, in <module>
    session = snowpark_utils.get_snowpark_session()
  File "/workspaces/sfguide-data-engineering-with-snowpark-python/utils/snowpark_utils.py", line 29, in get_snowpark_session
    SnowflakeConnection().connection = Session.builder.configs(snowpark_config).create()
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 315, in create
    session = self._create_internal(self._options.get("connection"))
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 344, in _create_internal
    ServerConnection({}, conn) if conn else ServerConnection(self._options),
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/snowpark/_internal/server_connection.py", line 136, in __init__
    self._conn = conn if conn else connect(**self._lower_case_parameters)
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 54, in Connect
    return SnowflakeConnection(**kwargs)
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/connection.py", line 372, in __init__
    self.connect(**kwargs)
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/connection.py", line 644, in connect
    self.__open_connection()
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/connection.py", line 917, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1186, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1212, in _authenticate
    auth.authenticate(
  File "/opt/conda/envs/snowflake-demo/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 259, in authenticate
    raise err.__class__(
snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. Verify the account name is correct: myaccount.snowflakecomputing.com:443. HTTP 403: Forbidden

**Comment by thanasitv** [comment]
I did't set ~/.snowsql/config
