### ISSUE TITLE
Build a Retrieval Augmented Generation(RAG) based LLM assistant using Streamlit, OpenAI and LlamaIndex

### ISSUE THREAD

**Issue by sfc-gh-dong** [Snowflake-Labs/sfquickstarts#993]
**Describe the bug**
Llama Index unable to read files in hidden directory .content, so it failed with this error while running python build_index.py
Building vector index...
Traceback (most recent call last):
  File "/Users/dong/sfguide-blog-ai-assistant/build_index.py", line 43, in <module>
    main()
  File "/Users/dong/sfguide-blog-ai-assistant/build_index.py", line 39, in main
    build_index(data_dir, knowledge_base_dir)
  File "/Users/dong/sfguide-blog-ai-assistant/build_index.py", line 23, in build_index
    documents = SimpleDirectoryReader(input_dir=d_dir, required_exts=required_exts, recursive=True).load_data()
  File "/Users/dong/sfguide-blog-ai-assistant/ai-assistant/lib/python3.9/site-packages/llama_index/readers/file/base.py", line 143, in __init__
    self.input_files = self._add_files(self.input_dir)
  File "/Users/dong/sfguide-blog-ai-assistant/ai-assistant/lib/python3.9/site-packages/llama_index/readers/file/base.py", line 204, in _add_files
    raise ValueError(f"No files found in {input_dir}.")
ValueError: No files found in /Users/dong/sfguide-blog-ai-assistant/.content/blogs.

Simply copying the files in .content/blog to another (non hidden) directory works.

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/build_rag_based_blog_ai_assistant_using_streamlit_openai_and_llamaindex/index.html?index=..%2F..index#3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobertDupuy** [comment]
I moved .content to content.

Seemed to have an issue with the "."

so 1) in the os:    mv .content content
2) in the code: data_dir = os.path.join(base_dir, "content", "blogs")

**Comment by RobertDupuy** [comment]
Ignore my earlier comment, upon reading your post better, I realize you know it is an issue with the hidden directory.

    documents = SimpleDirectoryReader(
            input_dir=data_dir,
            exclude_hidden=False,
            ).load_data()
